<?php
/**
 * Created by PhpStorm.
 * User: xushunbin
 * Date: 2018/3/17
 * Time: 15:48
 */

namespace app\models\base;


use yii\db\ActiveRecord;

class Articles extends ActiveRecord
{
    private static $saveFields = ['content','uid','lat','lng','address','thumbs','comments','status','created'];
    public static function tableName()
    {
        return 'articles'; // TODO: Change the autogenerated stub
    }
    /*
     * 插入数据
     * 2018年03月17日15:49:21
     */
    public static function insertItem($data){
        $m = new self();
        foreach(self::$saveFields as $v) {
            if(isset($data[$v])) $m -> $v = $data[$v];
        }
        $ret = $m -> save();
        if($ret) return $m -> attributes['id'];
        else return 0;
    }
}