<?php
namespace app\models\base;

class Users extends \yii\db\ActiveRecord
{
    /*
     * 数据库字段
     */
    private static $saveFields = ['account','password','created'];
    public static function tableName()
    {
        return 'users'; // TODO: Change the autogenerated stub
    }
    /*
     *  新建或编辑用户数据
     * 2018年03月05日22:37:37
     */
    public static function insertItem($data,$id=null) {
        if($id===null) $m = new Users();
        else $m = Users::findOne(['id'=>$id]);
        foreach(self::$saveFields as $v) {
            if(isset($data[$v])) $m -> $v = $data[$v];
        }
        if($m -> save()) return $m -> attributes['id'];
        else return false;
    }
}